[package]
name = "cs2"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"
authors = ["Hugo ARNAL <hugo@hugoarnal.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
clap = { version = "4.5.48", features = ["cargo", "derive"] }

