name: Format

on:
  push:
    branches: ["main"]
    paths:
      - "**.rs"
      - ".github/workflows/format.yml"
  pull_request:
    types: ["opened", "synchronize", "reopened"]
    paths:
      - "**.rs"
      - ".github/workflows/format.yml"
  workflow_dispatch:

jobs:
    check-format:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v5
        - run: cargo fmt --check
